import os, time, inspect
from decimal import Decimal
import run_production as r
import institutional_engine_v34 as e
print('==============================================')
print(' V3.4 REAL-KITE RECONCILIATION DIAGNOSTIC')
print('==============================================')
print('RUNNER =', r.__file__)
print('ENGINE =', e.__file__)
print('LIVE_TRADING_ENABLED =', r.LIVE_TRADING_ENABLED)
print('STATE_FILE =', r.STATE_FILE)
print('\n--- AUDIT IDENTITY ---')
print('Audit class =', r.ProductionAudit)
print('Audit log signature =', inspect.signature(r.ProductionAudit.log))
api_key = os.environ['KITE_API_KEY']
access_token = os.environ['KITE_ACCESS_TOKEN']
print('\n--- KITE CONNECTION ---')
kite = r.KiteConnect(api_key=api_key)
kite.set_access_token(access_token)
profile = kite.profile()
print('PROFILE USER ID =', profile.get('user_id'))
print('PROFILE USER NAME =', profile.get('user_name'))
print('\n--- BUILDING REAL BROKER ADAPTER ---')
broker = r.KiteBrokerAdapter(kite, live_trading=False)
audit = r.ProductionAudit()
store = r.JsonFileStore(r.STATE_FILE)
terminator = r.ProcessTerminator()
print('Broker adapter =', type(broker))
print('Audit object =', audit)
print('Store =', type(store))
print('Terminator =', type(terminator))
print('\n--- BUILDING ENGINE ---')
engine = e.TradingEngineV34(broker=broker, clock=r.SystemClock(), sleeper=time.sleep, store=store, audit=audit, alert=r.WebhookAlert(os.getenv('BOT_ALERT_WEBHOOK')), lock=r.SimpleFileLock(r.LOCK_FILE), terminator=terminator, cfg=e.Config(alert_webhook_url=os.getenv('BOT_ALERT_WEBHOOK') or '', max_daily_loss=Decimal('2000'), observation_retry_budget=3))
try:
    print('\n--- OBJECT IDENTITY ---')
    print('Passed audit ID =', id(audit))
    print('Engine audit ID =', id(engine.audit))
    print('Same audit object =', engine.audit is audit)
    print('Engine audit type =', type(engine.audit))
    print('Engine audit.log signature =', inspect.signature(engine.audit.log))
    print('\n--- PERSISTED STATE ---')
    print('State status =', engine.state.status)
    print('Active trade =', engine.state.active_trade)
    print('\n--- REAL BROKER POSITIONS (READ ONLY) ---')
    positions = broker.get_positions()
    print(positions)
    print('\n--- REAL BROKER ORDERS (READ ONLY) ---')
    orders = broker.get_orders()
    print(orders)
    print('\n--- DIRECT AUDIT TEST ---')
    engine.audit.log('REAL_KITE_DIAGNOSTIC', active_positions=len(positions), active_orders=len(orders))
    print('[PASS] Direct audit call succeeded.')
    print('\n--- STARTUP RECONCILIATION ---')
    engine.reconcile_startup()
    print('\n==============================================')
    print(' RECONCILIATION RETURNED SUCCESSFULLY')
    print('==============================================')
finally:
    print('\n--- RELEASING LOCK ---')
    try:
        engine.lock_provider.release()
        print('[OK] Engine lock released.')
    except Exception as exc:
        print('[WARNING] Lock release failed:', exc)
