"""FROZEN DESIGNATION: META_CONTROL_EXPERIMENT_V1 (2026-08-25).

Frozen per the owner's explicit architecture review: this is an OUTER-
LOOP research artifact only. It operates purely on CLOSED TRADE OUTCOMES
(net_pnl > 0) and must never read or modify anything in
study_layer_v2_state_vector.py's Layer-2 sensor states - confirmed by
construction (this file has no import of that module and never will;
mixing the two would let a slow, thin-sample, trade-outcome-driven loop
contaminate the fast, bar-level, evidence-driven one). Its candidate
future role, if any, is the slow OUTER adapter in the eventual two-loop
architecture (inner PI on desired-vs-actual exposure, outer adapter on
realized strategy quality) - not a replacement for either. Empirical
result on the V10-C 64-trade replay (see backtest_adaptive_threshold_on_
v10c.py, run 2026-08-25): static baseline -Rs.5,292.97; all 36 tested
gain combinations improved on that; best ~-Rs.98; NONE were net
profitable. Conclusion: this class of control can materially reduce
damage from a weak signal, but cannot manufacture alpha that isn't in
the underlying evidence - the loss-mitigation-not-alpha-creation finding
that motivated moving to the Layer-2 state-vector work instead of tuning
this controller further. Matches this project's own established freeze
convention (see e.g. the frozen P02 engine): do not edit this file's
behavior in place; a new candidate design becomes a new, separately-
versioned file.

Adaptive entry-threshold controller (2026-08-25, owner-requested).

Owner's question: "can we have a closed loop... or PID controllers here to
build up the main brain... not the... weighted average?" Answered in chat
before this file was written: a literal PID against PRICE is a category
error - this bot has no actuator over price, so there is no plant to
close a loop around there. But a PID DOES map cleanly onto a different,
real plant: the STRICTNESS OF THE BOT'S OWN ENTRY GATE, closed-loop
against the bot's OWN realized decision quality (trailing hit-rate of
trades it actually took). That loop is real: tightening the threshold
really does change which trades get taken, which really does change the
next window's measured hit-rate. This module implements exactly that,
nothing more:

    process variable (PV) = trailing hit-rate over the last `window`
                             CLOSED, ACTUALLY-TAKEN trades
    setpoint (SP)          = target_hit_rate
    error(t)               = SP - PV(t)   (positive = underperforming)
    output                 = Kp*error + Ki*clamp(integral) + Kd*(error-prev_error)
    new_threshold           = clip(base_threshold + output, min, max)

Positive error (underperforming) increases the threshold (stricter gate,
fewer future entries) via all three positive-signed terms; negative
error (outperforming) relaxes it. The integral term is hard-clamped
(anti-windup) so a long losing stretch cannot ratchet the threshold to
an absurd, never-recovering level - a documented, real hazard of naive
PID on a thin, non-stationary sample, not glossed over.

STRICT NO-LOOKAHEAD CONTRACT: current_threshold at "now" must depend
only on trades whose OUTCOME is already known as of "now" - never on the
trade currently being evaluated, and never on any future trade. Enforced
by construction (record_outcome() must be called AFTER a trade closes,
BEFORE evaluating the next candidate) and checked by
test_study_layer_v2_adaptive_threshold.py, matching the same discipline
as test_no_lookahead_regression.py elsewhere in this session.

Pure computation. No Kite/network calls. Not wired into any live engine.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field


@dataclass
class AdaptiveThresholdController:
    base_threshold: float
    target_hit_rate: float = 0.5
    kp: float = 0.0
    ki: float = 0.0
    kd: float = 0.0
    window: int = 10
    integral_clamp: float = 1.0          # anti-windup: |accumulated error| capped here
    threshold_min: float | None = None
    threshold_max: float | None = None

    _outcomes: deque = field(default_factory=lambda: deque(maxlen=None), repr=False)
    _integral: float = field(default=0.0, repr=False)
    # D term needs the error from the PREVIOUS record_outcome call, not a
    # value re-derived from the current (unchanged-since-then) state - see
    # the bug this replaced, caught by
    # test_derivative_term_reacts_to_rate_of_change_not_just_level.
    _prev_error: float = field(default=0.0, repr=False)
    _last_error: float = field(default=0.0, repr=False)
    _n_errors_recorded: int = field(default=0, repr=False)

    def __post_init__(self):
        # deque maxlen must be set from `window`, which dataclass field
        # defaults can't reference directly - fix it up here.
        self._outcomes = deque(maxlen=self.window)

    @property
    def n_outcomes_recorded(self) -> int:
        return len(self._outcomes)

    @property
    def trailing_hit_rate(self) -> float | None:
        """None until at least one outcome has been recorded - there is
        no honest hit-rate yet, and returning 0.0 or 0.5 would silently
        imply a measurement that doesn't exist."""
        if not self._outcomes:
            return None
        return sum(1 for w in self._outcomes if w) / len(self._outcomes)

    @property
    def current_threshold(self) -> float:
        """The threshold to apply to the NEXT candidate trade, given
        every outcome recorded so far. Before any outcome is recorded,
        this is simply base_threshold - the controller has no evidence
        yet to adjust anything, which is the correct, honest starting
        state, not an arbitrary guess."""
        if self.trailing_hit_rate is None:
            return self._clip(self.base_threshold)
        # P and I use _last_error - the error as of the most recent
        # record_outcome call - rather than recomputing it here, so the
        # value returned is exactly what the controller decided at that
        # step, not silently re-derived from state that hasn't changed
        # since (which is also why D below diffs two STORED errors
        # instead of "now vs stored", see the field comment above).
        p_term = self.kp * self._last_error
        i_term = self.ki * self._integral
        d_term = self.kd * (self._last_error - self._prev_error) if self._n_errors_recorded >= 2 else 0.0
        return self._clip(self.base_threshold + p_term + i_term + d_term)

    def record_outcome(self, won: bool) -> None:
        """Call this AFTER a trade CLOSES, with its real outcome (True =
        net profitable), BEFORE evaluating the next candidate. This is
        the only way state advances - current_threshold never looks at
        a trade that hasn't closed yet, by construction: nothing here
        ever reads a value the caller hasn't explicitly recorded."""
        self._outcomes.append(bool(won))
        hit_rate = self.trailing_hit_rate
        new_error = self.target_hit_rate - hit_rate
        self._integral = max(-self.integral_clamp, min(self.integral_clamp, self._integral + new_error))
        self._prev_error = self._last_error
        self._last_error = new_error
        self._n_errors_recorded += 1

    def _clip(self, value: float) -> float:
        if self.threshold_min is not None:
            value = max(self.threshold_min, value)
        if self.threshold_max is not None:
            value = min(self.threshold_max, value)
        return value
