import pathlib,json,hashlib,shutil,re
BASE=pathlib.Path('/home/srinivas/projects/zerodha-r5-governor-refactor/docs/r5_remediation_project')
SRC=pathlib.Path('/home/srinivas/Documents/Codex/2026-10-01/referenced-chatgpt-conversation-this-is-an/outputs/engine_code_audit')
NOTE=pathlib.Path('/home/srinivas/.codex/attachments/13c69bb1-7b69-4bbe-9e36-d2614ab459ec/Pasted text.txt')
archive=BASE/'archive';archive.mkdir(exist_ok=True)
entries=[]
def copy(src,dest):
 dest=archive/dest;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dest)
 entries.append({'original_path':str(src),'archive_path':str(dest.relative_to(BASE)),'sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'bytes':dest.stat().st_size})
for name in ['AUDIT_REPORT.md','DISPATCH_ECS_NOTE_CHECK.md','R5_Engine_Code_Authority_Audit.xlsx','source_manifest.json','workbook_data.json','workbook_inspection.json']:
 copy(SRC/name,name)
for f in sorted((SRC/'reviews').glob('*.json')):copy(f,pathlib.Path('reviews')/f.name)
copy(NOTE,'USER_REMEDIATION_NOTE.txt')
diagram=re.search(r'```mermaid\n(.*?)\n```',(SRC/'DISPATCH_ECS_NOTE_CHECK.md').read_text(),re.S).group(1)
(archive/'ARCHITECTURE_DIAGRAM.md').write_text('# Copied corrected source-audit diagram\n\n```mermaid\n'+diagram+'\n```\n\nSector bay identity is independent of A/B ownership. Dashed handoff is optional and absent from the default candidate worker. Static source diagram is not execution evidence.\n')
p=archive/'ARCHITECTURE_DIAGRAM.md';entries.append({'original_path':str(SRC/'DISPATCH_ECS_NOTE_CHECK.md')+' corrected implementation diagram','archive_path':str(p.relative_to(BASE)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
(archive/'archive_manifest.json').write_text(json.dumps({'schema_version':1,'purpose':'Immutable copies of existing audit artifacts; not raw reference datasets or remedial execution results.','files':entries},indent=2)+'\n')
ms=[('M00','Source audit and documentary baseline'),('M01','Isolated flat-outcome grading'),('M02','Authoritative fill and close bookkeeping'),('M03','Correlated conversion and ambiguity resolution'),('M04','Complete durable checkpoint and close feedback'),('M05','Protection, reconciliation and Engine B management'),('M06','Explicit integrated execution and evidence boundaries'),('M07','Sector dispatch and controller authority verification'),('M08','Current nonsealed controller and validation defects'),('M09','Historical, sealed and alternate-path disposition'),('M10','Integrated closeout and activity audit completion')]
activities=[]
def add(id,mid,title,classification,deps,criteria,evidence,findings=None,status='PLANNED',scope=None):
 activities.append({'id':id,'milestone':mid,'title':title,'classification':classification,'dependencies':deps,'acceptance_criteria':criteria,'evidence_required':evidence,'status':status,'source_finding_ids':findings or [],'scope':scope or 'Nonsealed opt-in remediation only; preserve frozen parameters, holdout quarantine and master reference outputs.','audit_report':f'audits/activities/{id}.md'})
add('DOC-001','M00','Archive completed source audit, note check, diagram and code workbook','document_correction',[],['All copied artifact SHA256 values equal their originals.','All 68 primary audit findings remain individually mapped; independent Claude cross-check retained separately.','Static source review is explicitly distinguished from execution proof.'],['archive/archive_manifest.json','archive/AUDIT_REPORT.md','archive/DISPATCH_ECS_NOTE_CHECK.md','archive/R5_Engine_Code_Authority_Audit.xlsx'],'',status='DONE',scope='Documentation copies only; no raw reference outputs changed.')
add('NOTE-01','M01','Apply and evaluate neutral flat-price grading in isolation','current_verified_repair',['DOC-001'],['Verify commit/diff content: unchanged grading-horizon price produces 0.5 for LONG and SHORT. Do not attribute this to causal_percentile_rank without source proof.','Change only studies grading; retain sampling, data, parameters, hold policy, governor and derivative damping.','Run baseline and corrected Block 1 through an explicit controlled entrypoint; report measured BUY/SELL, rejection funnel and ledger hashes without promising a direction shift.'],['Reviewed isolated diff and loaded source hashes','Equal flat LONG/SHORT unit outcomes','Baseline/corrected Block 1 manifests, ledgers and side/reason accounting'],['SIG-001'])
add('NOTE-02','M03','Resolve unknown conversion without blind retry or product-only promotion','integration_proof',['NOTE-01'],['Durable correlated request precedes broker call; unknown status blocks new risk and unverified exit routing.','Resolution verifies symbol, exchange, signed quantity, product, request identity, position ownership and protection rather than product alone.','Rejected, unknown, timeout, late ACK, duplicate ACK and close races have explicit recoverable dispositions; protective monitoring continues.'],['Fault-injected adapter receipts','Persisted request/state transitions','Restart and close-race evidence'],['N05','N06','ROOT-009'])
add('NOTE-03','M04','Recover complete controller/portfolio state and protective continuity','integration_proof',['NOTE-02'],['Select one coherent restart contract; persist complete ownership, trade, ledger, controller, exposure, cooldown and feedback state.','Broker truth and durable state reconcile before admission resumes.','Protective order capability, expiry and rearm receipts are explicit. Paper contingent orders and live GTT are different; neither product CNC nor GTT guarantees a fill. Fixed 0.995 limit multiplier is not adopted as an unverified universal policy.'],['Versioned checkpoint schema and source/config identity','Interrupted/uninterrupted equivalence','Missing/expired/mismatched protection and broker reconciliation fixtures'],['N03','N04','N15','ROOT-010','ROOT-015'])
add('NOTE-04','M07','Preserve one exposure-headroom application and document fleet controller scope','no_change',['DOC-001'],['Trace ECS demand, merit weights inside sector water-filling, bay references and current exposure headroom through actual active call sites.','Do not add a second current-exposure subtraction. Do not claim every possible fleet PID necessarily doubles exposure subtraction.','A new fleet PID remains separately scoped until reference, measured exposure, dt, saturation/antiwindup and single actuator contract are approved.'],['Mode-labelled loading/headroom trace','Algebra and capacity-bound fixtures','Explicit prototype/default import map'],['N12','ROOT-014'])
add('NOTE-05','M06','Use explicit opt-in runtime rather than handoff-config-only enablement','integration_proof',['NOTE-03'],['An explicit experimental constructor supplies runtime and selected recovery integration; sealed candidate worker remains unchanged.','Qualified completed BUY bar requires current R and MFE >=0.75, causal alignment and exchange-local 15:10–15:14 window under explicit opt-in policy.','Actual filled trade reaches verified conversion, B management and broker/protection reconciliation; constructor flags alone are insufficient.'],['Mode/constructor manifest','Full orchestrator.run lifecycle trace and ledger','Default behavior parity and quarantine checks'],['ROOT-002','ROOT-008'])
add('NOTE-06','M07','Verify canonical sector close feedback without remapping A into steam bays','integration_proof',['DOC-001'],['TITAN remains CSTG2 and RELIANCE remains GTG1 through A/B ownership changes.','Measured per-bay close counts and realized-R consumer receipts demonstrate actual feedback, including direct A steam-sector trades.','Mapping remains unchanged; process-local exactly-once weakness is addressed by durable per-consumer work, not by claiming current mapping guarantees delivery.'],['Canonical universe mapping digest','Per-trade and per-bay feedback receipts','No bay-remapping diff'],['N07','ROOT-004'])
add('NOTE-07','M06','Correct note runner/provenance and causal interpretation','document_correction',['DOC-001'],['Record actual branch/head and isolated grading diff; do not blindly assume attachment head matches repository.','Document all required runner arguments and sealed parent identity restrictions; incomplete --block 1 pseudocommand is not acceptance evidence.','Do not use 53 SELL/1 BUY as new measured baseline or promise that grading explains entire asymmetry.'],['Reviewed CLI interface','Experimental runner manifest','Note-to-source correction report'],['ROOT-008','SIG-001'])
# Finding classifications are deliberate dispositions, not automatic permission to alter sealed/historical code.
repair={'N01','N02','N05','N06','N07','N14','ROOT-001','ROOT-004','ROOT-005','ROOT-006','ROOT-012','SIG-001','SIG-009','SIG-010','SIG-011','SIG-014'}
proof={'N03','N04','N15','ROOT-002','ROOT-007','ROOT-008','ROOT-009','ROOT-010','ROOT-015','SIG-003','SIG-004','SIG-006','SIG-012','SIG-013'}
nochange={'N08','N12','N16','ROOT-003','ROOT-014','SIG-005'}
compare={'N09','N10','N13','LEG-006','LEG-007','LEG-009','LEG-010','LEG-011','LEG-012','LEG-014','LEG-016','LEG-017','LEG-018','LEG-020','LEG-021','ROOT-012','SIG-007','SIG-008'}
midmap={'N01':'M02','N02':'M02','N03':'M04','N04':'M04','N05':'M03','N06':'M03','N07':'M04','N14':'M05','N15':'M04','ROOT-001':'M02','ROOT-002':'M06','ROOT-004':'M04','ROOT-005':'M02','ROOT-006':'M05','ROOT-007':'M06','ROOT-008':'M06','ROOT-009':'M03','ROOT-010':'M05','ROOT-015':'M04','SIG-001':'M01','SIG-003':'M06','SIG-004':'M06','SIG-006':'M07','SIG-012':'M07','SIG-013':'M08'}
findings=[]
for name in ['native_review.json','root_review.json','signals_review.json','legacy_review.json']:
 for f in json.loads((SRC/'reviews'/name).read_text())['findings']:
  fid=f['id'];findings.append(fid)
  cat='current_verified_repair' if fid in repair else 'integration_proof' if fid in proof else 'no_change' if fid in nochange else 'historical_comparison' if fid.startswith('LEG-') or fid in compare else 'document_correction'
  mid=midmap.get(fid,'M09' if cat=='historical_comparison' or fid.startswith('LEG-') else 'M08' if cat=='current_verified_repair' else 'M07')
  dep=['DOC-001'] if mid in ['M01','M07','M09'] else ['NOTE-01']
  criteria=[f['action']]
  if cat=='current_verified_repair':
   criteria+=['An isolated nonsealed diff addresses the cited trigger; a focused regression reproduces the source defect and verifies the corrected disposition.','Unchanged controls and authoritative ledger/reference boundaries are recorded; no result is declared until the evidence is attached.']
  elif cat=='integration_proof':criteria+=['Evidence comes from the actual selected orchestrator execution path and named mode, not helper existence or import alone.','Unexpected, delayed, missing and restart outcomes are explicitly dispositioned without inventing broker protection or exactly-once delivery.']
  elif cat=='historical_comparison':criteria+=['Identify historical/sealed/alternate caller and loaded/default status; record this defect as comparison or a separately scoped repair.','Do not change sealed V3 or silently transfer historical controller results to current R5.']
  elif cat=='no_change':criteria+=['Keep the current behavior unchanged until a separately isolated design/test requirement is approved; document exact actuator and mode limitations.']
  else:criteria+=['Publish precise source-backed authority/caller/consumer correction; retain static-versus-runtime distinction.']
  add('F-'+fid,mid,f['claim'],cat,dep,criteria,[{'source_review':f'archive/reviews/{name}','source_evidence':f.get('evidence',[])},'Activity audit records exact tested command, fixture, code/data identity and result, or explicitly NOT RUN'],[fid])
assert len(findings)==68 and len(set(findings))==68
add('VERIFY-01','M10','Accept integrated paper lifecycle and close project evidence gaps','integration_proof',[a['id'] for a in activities if a['id']!='DOC-001'],['Every finding has a completed audit or explicit reviewed deferral/disposition; unresolved critical implementation activities block readiness.','Execute opt-in A fill→qualified conversion→B hold/trailing→protective/third-session close→restart/reconcile with fault cases and per-consumer durable feedback.','Show default/sealed parity, frozen parameter/data identities, fixed universe/session boundaries and no holdout/master reference mutation.','Report paper versus live capability separately; no trading-system certification or live protection guarantee follows from paper acceptance.'],['Milestone acceptance receipts','Integrated execution/fault evidence','Comparative ledger and source/config/data hashes','Final unresolved-issues register'])
obj={'schema_version':1,'basis':'Full static audit plus latest remediation note. Status describes remediation evidence, not source-review completion.','classification_legend':{'current_verified_repair':'Source defect verified; repair and regression still required.','historical_comparison':'Historical/sealed/alternate defect, preserved and separately dispositioned.','document_correction':'Correct architecture/authority claim using copied source evidence.','no_change':'Preserve present behavior; verify/document contract rather than automatic redesign.','integration_proof':'Prove actual end-to-end invocation/recovery/authority under explicit mode.'},'constraints':['No dates or durations','No invented completion or certification','Sector bays are independent of A/B lifecycle ownership','CNC/GTT does not guarantee live protective fill','No universal claim that any fleet PID double-subtracts exposure','No sealed V3, frozen parameter, holdout or master-reference mutation'],'primary_finding_count':68,'activities':activities}
(BASE/'activities.json').write_text(json.dumps(obj,indent=2)+'\n')
msout=[]
for mid,title in ms:
 ids=[a['id'] for a in activities if a['milestone']==mid]
 msout.append({'id':mid,'title':title,'activities':ids,'status':'DONE' if mid=='M00' else 'PLANNED','audit_report':f'audits/milestones/{mid}.md','exit_criteria':['All listed activities have evidence-backed acceptance or explicit reviewed disposition.','No unresolved prerequisite is represented as passed.']})
for i,m in enumerate(msout):
 m['acceptance_dependencies']=[msout[i-1]['id']] if i else []
 m['execution_rule']='Preparatory source review may proceed independently; acceptance is released only after the previous milestone receipt and activity dependencies close.'
(BASE/'milestones.json').write_text(json.dumps({'milestones':msout},indent=2)+'\n')
for a in activities:
 p=BASE/a['audit_report'];p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text(f"# {a['id']} activity audit\n\nStatus: {a['status']}\n\nMilestone: {a['milestone']}\n\nClassification: {a['classification']}\n\nScope: {a['scope']}\n\n## Required result\n\n"+'\n'.join('- '+str(c) for c in a['acceptance_criteria'])+'\n\n## Dependencies\n\n'+', '.join(a['dependencies'])+'\n\n## Evidence\n\n'+('Copied source audit and SHA evidence: archive/archive_manifest.json. Documentation archive only; remediation tests NOT RUN.\n' if a['status']=='DONE' else 'NOT RUN. Attach exact code/config/data identity, fixture or command, expected result, actual result, logs and relevant hashes.\n')+'\n## Decision and remaining issues\n\n'+('Archive complete; no claim of repaired engine or runtime certification.\n' if a['status']=='DONE' else 'PENDING. Record PASS / FAIL / DEFERRED with the evidence and reviewer disposition. No acceptance is implied by this template.\n'))
for m in msout:
 p=BASE/m['audit_report'];p.parent.mkdir(parents=True,exist_ok=True);p.write_text(f"# {m['id']} milestone audit\n\n{m['title']}\n\nStatus: {m['status']}\n\n## Activity receipts\n\n"+'\n'.join('- ['+id+'](../activities/'+id+'.md)' for id in m['activities'])+'\n\n## Acceptance decision\n\n'+('DONE for copied source audit documentation only. Hash evidence is in archive/archive_manifest.json.\n' if m['status']=='DONE' else 'PENDING. Verify predecessor evidence and all activity receipts. List remaining failures, approved dispositions, rollback and scope limitations.\n'))
(BASE/'PROJECT_EXECUTION_ORDER.md').write_text('# R5 remediation execution project\n\nThis is an ordered evidence plan. The source audit is complete; repair, integration and certification are separate. Only the copied documentation baseline is marked DONE. Engine work and new execution evidence remain PLANNED in this deliverable.\n\n'+ '\n'.join(f'{i}. **{mid}: {title}** — '+('DONE: copied audit/archive evidence.' if mid=='M00' else 'PLANNED: acceptance requires the listed activity receipts.') for i,(mid,title) in enumerate(ms,1))+'\n\nDependencies are explicit per activity in activities.json; milestone numbering groups acceptance work and does not fabricate elapsed time. Isolated grading precedes structural-change acceptance. Historical/sealed defects are dispositions, not authorization to rewrite sealed references.\n\n## Deliverable map\n\n- activities.json: every primary finding and every proposed note solution, criteria and evidence.\n- milestones.json: milestone membership and acceptance reports.\n- audits/activities/: one evidence report per activity.\n- audits/milestones/: one acceptance report per milestone.\n- archive/: complete existing audit reports, source-review JSON, workbook, corrected diagram and latest note.\n- archive/archive_manifest.json: copied artifact identities.\n\nNo raw reference dataset or master ledger is copied/modified. Do not infer live readiness from PAPER_APPLY success.\n')
print(json.dumps({'activities':len(activities),'primary_findings':len(findings),'milestones':len(msout),'copied_artifacts':len(entries),'done':[a['id'] for a in activities if a['status']=='DONE']}))
