#!/usr/bin/env python3
"""
Download real NIFTY 50 data from Zerodha using provided credentials.

User provided:
  - API key: f5qmn3ug0i6brql3
  - Client ID: CE2003
  - Request token from redirect: l21awlXxNkMZReO5AsSDixjz3dW15IIy

Steps:
  1. Generate access_token from request_token
  2. Fetch NIFTY 50 minute-level data
  3. Save as CSV for use in backtests
"""

import sys
import os
import json
import hashlib
import requests
import pandas as pd
from datetime import datetime, timedelta

print('\n' + '='*160)
print('ZERODHA NIFTY 50 DATA DOWNLOAD')
print('='*160 + '\n')

# Credentials
API_KEY = "f5qmn3ug0i6brql3"
CLIENT_ID = "CE2003"
REQUEST_TOKEN = "l21awlXxNkMZReO5AsSDixjz3dW15IIy"

# Note: API_SECRET is required but not provided
# Typical secret format is auto-generated by Zerodha after app creation
# Since we don't have it, we'll attempt auth and show clear error if needed

print('[1] Attempting to generate access_token from request_token')
print('-'*160)
print(f'API Key: {API_KEY}')
print(f'Client ID: {CLIENT_ID}')
print(f'Request Token: {REQUEST_TOKEN}')
print()

# Step 1: Try to get access_token
# This requires the API_SECRET which we don't have
print('⚠️  ISSUE: API_SECRET is required but not provided')
print()
print('To complete authentication, we need the API_SECRET from Zerodha app credentials.')
print('This is auto-generated when you create an app on Zerodha\'s developer console.')
print()
print('Without it, the auth will fail with "Invalid checksum".')
print()

print('='*160)
print('OPTIONS:')
print('='*160 + '\n')

print('Option 1: Manual Token Exchange')
print('  1. Go to https://kite.zerodha.com/connect/login?v=3&app_id={API_KEY}')
print('  2. Use credentials to login')
print('  3. You\'ll get a new request_token')
print('  4. Provide both request_token AND api_secret')
print()

print('Option 2: If you have API_SECRET:')
print('  1. Set API_SECRET environment variable: export ZERODHA_API_SECRET="..."')
print('  2. Re-run this script')
print()

print('Option 3: Use cached/downloaded NIFTY data')
print('  1. Download NIFTY 50 from alternative source (TradingView, Yahoo Finance, etc.)')
print('  2. Save as CSV in data/ directory')
print()

print('='*160)
print()

# Try to get API_SECRET from environment
API_SECRET = os.environ.get('ZERODHA_API_SECRET')

if API_SECRET:
    print(f'[2] Found API_SECRET in environment, attempting auth...\n')

    # Generate checksum
    checksum_input = f"{API_KEY}{REQUEST_TOKEN}{API_SECRET}"
    checksum = hashlib.sha256(checksum_input.encode()).hexdigest()

    print(f'Checksum: {checksum}\n')

    # Exchange request_token for access_token
    auth_url = "https://api.kite.trade/session/token"
    auth_payload = {
        "api_key": API_KEY,
        "request_token": REQUEST_TOKEN,
        "checksum": checksum
    }

    print('[3] Exchanging request_token for access_token...')

    try:
        response = requests.post(auth_url, data=auth_payload)
        response.raise_for_status()

        auth_result = response.json()

        if "data" in auth_result and "access_token" in auth_result["data"]:
            access_token = auth_result["data"]["access_token"]
            print(f'✓ Access token obtained: {access_token[:20]}...\n')

            # Now download NIFTY data
            print('[4] Downloading NIFTY 50 data...\n')

            headers = {
                "Authorization": f"Bearer {API_KEY} {access_token}",
                "X-Kite-Version": "3"
            }

            # NIFTY 50 instrument token is 256265
            instrument_token = 256265

            # Get data for last 6 months
            end_date = datetime.now()
            start_date = end_date - timedelta(days=180)

            data_url = f"https://api.kite.trade/instruments/historical/{instrument_token}/minute"
            params = {
                "from": start_date.strftime("%Y-%m-%d"),
                "to": end_date.strftime("%Y-%m-%d"),
                "continuous": 0,
                "oi": 1
            }

            print(f'URL: {data_url}')
            print(f'Date range: {start_date.date()} to {end_date.date()}\n')

            data_response = requests.get(data_url, headers=headers, params=params)
            data_response.raise_for_status()

            data_result = data_response.json()

            if "data" in data_result and "candles" in data_result["data"]:
                candles = data_result["data"]["candles"]
                print(f'✓ Downloaded {len(candles)} candles\n')

                # Convert to DataFrame
                df = pd.DataFrame(candles, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume', 'oi'])
                df['timestamp'] = pd.to_datetime(df['timestamp'])

                print(f'Date range: {df["timestamp"].min()} to {df["timestamp"].max()}')
                print(f'Rows: {len(df)}')
                print(f'Close range: ₹{df["close"].min():.2f} to ₹{df["close"].max():.2f}\n')

                # Save to CSV
                output_path = 'data/NIFTY_50_real.csv'
                os.makedirs(os.path.dirname(output_path), exist_ok=True)
                df.to_csv(output_path, index=False)

                print(f'✓ Saved to {output_path}\n')
                print('='*160)
                print('SUCCESS: Real NIFTY 50 data downloaded and saved')
                print('='*160 + '\n')
            else:
                print(f'✗ No candle data returned: {data_result}')
        else:
            print(f'✗ Auth failed: {auth_result}')

    except requests.exceptions.RequestException as e:
        print(f'✗ Request failed: {e}\n')
        print('This is expected if API_SECRET is incorrect.')

else:
    print('[!] API_SECRET not found in environment')
    print('    Set it and try again: export ZERODHA_API_SECRET="your-secret"\n')

print('='*160 + '\n')
